package gui;

import com.ozten.font.JFontChooser;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.PrintWriter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author USER
 */
public class MyNotepad extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form MyNotepad
     */
    public MyNotepad() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        popupMenu = new javax.swing.JPopupMenu();
        mnuNew2 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtContent = new javax.swing.JTextArea();
        jMenuBar2 = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        MnuNew = new javax.swing.JMenuItem();
        mnuOpen = new javax.swing.JMenuItem();
        mnuSave = new javax.swing.JMenuItem();
        mnuSaveAs = new javax.swing.JMenuItem();
        mnuneewwww = new javax.swing.JMenuItem();
        mnFileReplace = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        mnuFormat = new javax.swing.JMenu();
        mnuFont = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        mnuNew2.setText("New\n");
        mnuNew2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNew2ActionPerformed(evt);
            }
        });
        popupMenu.add(mnuNew2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtxtContent.setColumns(20);
        jtxtContent.setRows(5);
        jtxtContent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtContentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtxtContent);

        mnuFile.setText("File");

        MnuNew.setText("New");
        MnuNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuNewActionPerformed(evt);
            }
        });
        mnuFile.add(MnuNew);

        mnuOpen.setText("Open");
        mnuOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuOpenActionPerformed(evt);
            }
        });
        mnuFile.add(mnuOpen);

        mnuSave.setText("Save");
        mnuSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSaveActionPerformed(evt);
            }
        });
        mnuFile.add(mnuSave);

        mnuSaveAs.setText("Save As");
        mnuFile.add(mnuSaveAs);

        mnuneewwww.setText("New Window");
        mnuneewwww.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuneewwwwActionPerformed(evt);
            }
        });
        mnuFile.add(mnuneewwww);

        jMenuBar2.add(mnuFile);

        mnFileReplace.setText("Edit");

        jMenuItem2.setText("Find and replace");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mnFileReplace.add(jMenuItem2);

        jMenuBar2.add(mnFileReplace);

        mnuFormat.setText("Format");

        mnuFont.setText("Font");
        mnuFont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFontActionPerformed(evt);
            }
        });
        mnuFormat.add(mnuFont);

        jMenuBar2.add(mnuFormat);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuOpenActionPerformed
        // TODO add your handling code here:
        String s = jtxtContent.getText();
        if (!s.isEmpty()) {
            // neu ope n file ma noi dung cu dang co ma can luu lai noi dung nay copy code mnNew vao day

        } else {
            JFileChooser fc = new JFileChooser();
            if (fc.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
                File f = fc.getSelectedFile();
                FileReader ff = null;
                BufferedReader r = null;
                try {
                    setTitle(f.getName());
                    ff = new FileReader(f);
                    r = new BufferedReader(ff);
                    while (r.ready()) {
                        jtxtContent.setText(jtxtContent.getText() + r.readLine());
                    }

                } catch (Exception e) {
                    e.printStackTrace();
                } finally {
                    try {
                        if (ff != null) {
                            ff.close();
                        }
                        if (r != null) {
                            r.close();
                        }
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            }
         
    
            
        }
    }//GEN-LAST:event_mnuOpenActionPerformed

    private void mnuSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuSaveActionPerformed

    private void MnuNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuNewActionPerformed
        // TODO add your handling code here:
        String s = jtxtContent.getText();
        if (!s.isEmpty()) {
            // luu noi dung cu lai truoc khi new moi
            JFileChooser fc = new JFileChooser();
            int result = fc.showSaveDialog(null);
            if (result == JFileChooser.APPROVE_OPTION) {
                // ghi text file
                // lay ten file user dachon trong JflieChooser
                File f = fc.getSelectedFile();
                if (f.exists()) {
                    int ans = JOptionPane.showConfirmDialog(null, "Do you want to replace all", "Hoi ngu ti", JOptionPane.YES_NO_OPTION);
                    if (ans == JOptionPane.YES_OPTION) {
                        JOptionPane.showMessageDialog(null, "ghet thang kia");
                    } else {
                        JOptionPane.showMessageDialog(null, "thuong thang kia");
                    }
                }
                PrintWriter w = null;
                try {
                    w = new PrintWriter(f);
                    w.println(s);
                    jtxtContent.setText("");
                } catch (Exception e) {
                    e.printStackTrace();
                } finally {
                    try {
                        if (w != null) {
                            w.close();
                        }
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            } else {
                jtxtContent.setText("");
            }
        }
  
    }//GEN-LAST:event_MnuNewActionPerformed

    private void mnuneewwwwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuneewwwwActionPerformed
        // TODO add your handling code here:
        Thread t = new Thread(this, "new");
        t.run();
    }//GEN-LAST:event_mnuneewwwwActionPerformed

    private void jtxtContentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtContentMouseClicked
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        if (evt.getButton() == 3) {
            popupMenu.show(null, x, y);
        } else {
            popupMenu.setVisible(false);
        }


    }//GEN-LAST:event_jtxtContentMouseClicked

    private void mnuNew2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNew2ActionPerformed
        // TODO add your handling code here:
        System.out.println("a");
    }//GEN-LAST:event_mnuNew2ActionPerformed

    private void mnuFontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFontActionPerformed
        // TODO add your handling code here:
        Font mf = new JFontChooser().showDialog(this, "Choose font:"); // chua dap an cua ham nay
        if (mf != null) {
            jtxtContent.setFont(mf);
        }

    }//GEN-LAST:event_mnuFontActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        Font_replace dlg = new Font_replace(this, true);
        dlg.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyNotepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyNotepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyNotepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyNotepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyNotepad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MnuNew;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea jtxtContent;
    private javax.swing.JMenu mnFileReplace;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenuItem mnuFont;
    private javax.swing.JMenu mnuFormat;
    private javax.swing.JMenuItem mnuNew2;
    private javax.swing.JMenuItem mnuOpen;
    private javax.swing.JMenuItem mnuSave;
    private javax.swing.JMenuItem mnuSaveAs;
    private javax.swing.JMenuItem mnuneewwww;
    private javax.swing.JPopupMenu popupMenu;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        MyNotepad fv = new MyNotepad();
        fv.setVisible(true);
    }
}
