/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DTO.Product;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class ItemPanel extends javax.swing.JPanel {

    /**
     * Creates new form SupplierPanel
     */
    boolean themmoi = true;
    
    public ItemPanel() {
        initComponents();
        loadItem();
        this.setSize(1000, 1400);
        spinnerGia.setEnabled(false);
        txtMaMH.setEnabled(false);
        txtTenMH.setEnabled(false);
        cbxSuplier.setEnabled(false);
        
    }
     public static boolean checkC(Vector<Product> product, String supplier) {
         for (Product product1 : product) {
             if(product1.getSupplier().equals(supplier))
                 return true;
         }
        return false;
    }
    void loadItem() {
        Vector header = DAO.SupplierDAO.getColumProduct();
        
        Vector data = new Vector();
        Vector<Product> list = DAO.SupplierDAO.getProduct();
        for (Product product : list) {
             Vector row = new Vector();
             row.add(product.getId());
             row.add(product.getName());
             row.add(product.getPrice());
             row.add(product.getSupplier());
             
             
             data.add(row);

             
        }
        
            DefaultTableModel model = (DefaultTableModel) tableSanPham.getModel();
            model.setDataVector(data, header);
            /**
             * This method is called from within the constructor to initialize
             * the form. WARNING: Do NOT modify this code. The content of this
             * method is always regenerated by the Form Editor.
             */
        
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableSanPham = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMaMH = new javax.swing.JTextField();
        txtTenMH = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnHuyThaoTac = new javax.swing.JButton();
        btnXuatBaoCao = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        spinnerGia = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        cbxSuplier = new javax.swing.JComboBox<>();

        tableSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableSanPham.getTableHeader().setReorderingAllowed(false);
        tableSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSanPhamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableSanPham);

        jLabel1.setText("Ma MH");

        jLabel2.setText("Ten MH");

        btnThem.setText("Them moi");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sua");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnLuu.setText("Luu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnXoa.setText("Xoa");

        btnHuyThaoTac.setText("Huy Thao Tac");

        btnXuatBaoCao.setText("Xuat bao cao");
        btnXuatBaoCao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatBaoCaoActionPerformed(evt);
            }
        });

        jLabel3.setText("Gia");

        spinnerGia.setModel(new javax.swing.SpinnerNumberModel(1000, 1000, 1000000, 500));
        spinnerGia.setMaximumSize(new java.awt.Dimension(1000000, 1000000));

        jLabel4.setText("Nha cung cap");

        cbxSuplier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "coca", "pepsi", "7up" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnThem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSua))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnXoa)
                                .addGap(18, 18, 18)
                                .addComponent(btnHuyThaoTac)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnXuatBaoCao)
                            .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(49, 49, 49)
                                .addComponent(cbxSuplier, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(76, 76, 76)
                                .addComponent(spinnerGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(txtMaMH, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(txtTenMH)))))
                .addContainerGap(388, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtMaMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtTenMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(spinnerGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cbxSuplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem)
                            .addComponent(btnSua)
                            .addComponent(btnLuu))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnXoa)
                            .addComponent(btnHuyThaoTac)
                            .addComponent(btnXuatBaoCao)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(344, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnXuatBaoCaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatBaoCaoActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_btnXuatBaoCaoActionPerformed

    private void tableSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSanPhamMouseClicked
        // TODO add your handling code here:
        spinnerGia.setEnabled(false);
        txtMaMH.setEnabled(false);
        txtTenMH.setEnabled(false);
        cbxSuplier.setEnabled(false);
        int pos = tableSanPham.getSelectedRow();
        int code = (int) tableSanPham.getValueAt(pos, 0);
        Vector<Product> list = DAO.SupplierDAO.getProduct();
        Product p = null;
        for (Product product : list) {
            if (product.getId() == code) {
                p = product;
                break;
            }
        }
        if (pos >= 0) {
            txtMaMH.setText(((Integer) tableSanPham.getValueAt(pos, 0)).toString());
            txtTenMH.setText((String) tableSanPham.getValueAt(pos, 1));
            spinnerGia.setValue(tableSanPham.getValueAt(pos, 2));
            
            DefaultComboBoxModel dd = (DefaultComboBoxModel) cbxSuplier.getModel();
            
            dd.setSelectedItem(p.getSupplier());
            ;
        }
    }//GEN-LAST:event_tableSanPhamMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        themmoi = true;
        txtMaMH.setEnabled(true);
        txtTenMH.setEnabled(true);
        spinnerGia.setEnabled(true);
        cbxSuplier.setEnabled(true);
        txtMaMH.setText("");
        txtTenMH.setText("");
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(txtMaMH.getText().trim());
            String name = txtTenMH.getText();
            int price = (int) spinnerGia.getValue();
            String supplier = (String) cbxSuplier.getSelectedItem();
            int idSupplier = 0;
            if (supplier.equalsIgnoreCase("coca")) {
                idSupplier = 0;
            } else if (supplier.equalsIgnoreCase("larue")) {
                idSupplier = 1;
            } else if (supplier.equalsIgnoreCase("7up")) {
                idSupplier = 2;
            }
            if (themmoi) {
                if (DAO.SupplierDAO.insertProduct(id, name, price, idSupplier) != 0) {
                    JOptionPane.showMessageDialog(null, "Them thanh cong");
                    loadItem();
                    DefaultComboBoxModel model = (DefaultComboBoxModel) tableSanPham.getModel();
                    
                } else {
                    JOptionPane.showMessageDialog(null, "Them that bai");
                }
                txtMaMH.setEnabled(false);
                txtTenMH.setEnabled(false);
                spinnerGia.setEnabled(false);
                cbxSuplier.setEnabled(false);
                txtMaMH.setText("");
                txtTenMH.setText("");
            }else{
                Vector<Product> list = DAO.SupplierDAO.getProduct();
                int pos = tableSanPham.getSelectedRow();
                Product p = list.get(pos);
                int oldId = p.getId();
                if(DAO.SupplierDAO.updateProduct(id, name, price, idSupplier,oldId) != 0){
                     JOptionPane.showMessageDialog(null, "update thanh cong");
                    loadItem();
                }else{
                    JOptionPane.showMessageDialog(null, "update that bai");
                }
            }
        } catch (Exception e) {
               if (e.getMessage().contains("Cannot insert duplicate key")) {
                JOptionPane.showMessageDialog(null, "ID trung");
            } else {
                JOptionPane.showMessageDialog(null, "Ma, ten nha cung cap bi sai");
            }
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        themmoi = false;
        txtMaMH.setEnabled(false);
        txtTenMH.setEnabled(true);
        spinnerGia.setEnabled(true);
        cbxSuplier.setEnabled(true);
    }//GEN-LAST:event_btnSuaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuyThaoTac;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXuatBaoCao;
    private javax.swing.JComboBox<String> cbxSuplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spinnerGia;
    private javax.swing.JTable tableSanPham;
    private javax.swing.JTextField txtMaMH;
    private javax.swing.JTextField txtTenMH;
    // End of variables declaration//GEN-END:variables
}
