/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.DBUtil;
import java.text.DateFormat;
import java.text.MessageFormat;
import java.text.NumberFormat;
import java.util.Date;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class JframeForm extends javax.swing.JFrame {

    /**
     * Creates new form JframeForm
     */
    Locale current;

    public JframeForm() {
        initComponents();
        setLocationRelativeTo(this);
        loadLanguage();
    }

    void loadLanguage() {
        if (rdbTV.isSelected()) {
            current = new Locale("vn", "VN");

        } else {
            current = new Locale("en", "US");
        }
        //NAP FILE PROPERTIES
        ResourceBundle rs = ResourceBundle.getBundle("NgonNgu.thanghung", current);
        lblEmail.setText(rs.getString("key1"));
        jLabel2.setText(rs.getString("key2"));
        btnDangNhap.setText(rs.getString("key3"));
        rdbTV.setText(rs.getString("key4"));
        rdbTA.setText(rs.getString("key5"));
        // cho nay de hc cach format date, time
        DateFormat DF = DateFormat.getDateInstance(DateFormat.LONG, current);
        String s = DF.format(new Date());
        JOptionPane.showMessageDialog(null, s);
        
        // cho nay la don vi tien te
        NumberFormat nf = NumberFormat.getCurrencyInstance(current);
        String tien = nf.format(1000);
        JOptionPane.showMessageDialog(null, tien);
        
        // cho nay de thong bao theo ngon ngu dang chon, co nhung data cua chuong trinh
        Object[] data = {new Integer(100),new Date()};
        MessageFormat mf = new MessageFormat(rs.getString("key6"), current);
        String msg = mf.format(data);
        JOptionPane.showMessageDialog(null, msg);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblEmail = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtPass = new javax.swing.JTextField();
        btnDangNhap = new javax.swing.JButton();
        rdbTV = new javax.swing.JRadioButton();
        rdbTA = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblEmail.setText("email");

        jLabel2.setText("mat khau");

        txtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPassKeyReleased(evt);
            }
        });

        btnDangNhap.setText("Dang Nhap");
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbTV);
        rdbTV.setSelected(true);
        rdbTV.setText("Tieng Viet");
        rdbTV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbTVActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbTA);
        rdbTA.setText("Tieng Anh");
        rdbTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbTAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(lblEmail))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(rdbTV)
                        .addGap(47, 47, 47)
                        .addComponent(rdbTA)
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(btnDangNhap)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail)
                    .addComponent(rdbTV)
                    .addComponent(rdbTA))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnDangNhap)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        // TODO add your handling code here:
        String email = txtEmail.getText();
        String pass = txtPass.getText();
        String name = DBUtil.checkLogin(email, pass);

        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Dang nhap lai");

        } else {
            MainFrame mf = new MainFrame(name);
            mf.setVisible(true);
            this.dispose();
        }


    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void txtPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassKeyReleased
        System.out.println(evt.getKeyCode());
        if (evt.getKeyCode() == 10) {
            btnDangNhapActionPerformed(null);
        }
    }//GEN-LAST:event_txtPassKeyReleased

    private void rdbTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbTAActionPerformed
        // TODO add your handling code here:
        rdbTA.setSelected(true);
        loadLanguage();
    }//GEN-LAST:event_rdbTAActionPerformed

    private void rdbTVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbTVActionPerformed
        // TODO add your handling code here:
        rdbTV.setSelected(true);
        loadLanguage();
    }//GEN-LAST:event_rdbTVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JframeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JframeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JframeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JframeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JframeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangNhap;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JRadioButton rdbTA;
    private javax.swing.JRadioButton rdbTV;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtPass;
    // End of variables declaration//GEN-END:variables
}
