/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package baitap1;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JColorChooser;

/**
 *
 * @author USER
 */
public class frame1 extends javax.swing.JFrame {

    /**
     * Creates new form frame1
     */
    int x1, y1;
    int x2, y2;
    int shape = 1;
    Color c;
    boolean xoa = false;
    public frame1() {
        initComponents();
        c = Color.BLACK;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        rdoLine = new javax.swing.JRadioButton();
        rdoRec = new javax.swing.JRadioButton();
        rdoOval = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        rdoFill = new javax.swing.JRadioButton();
        rdoNotFill = new javax.swing.JRadioButton();
        btnChooseColor = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(rdoLine);
        rdoLine.setSelected(true);
        rdoLine.setText("Line");
        rdoLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoLineActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoRec);
        rdoRec.setText("Rectangle");
        rdoRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoRecActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoOval);
        rdoOval.setText("Oval");
        rdoOval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoOvalActionPerformed(evt);
            }
        });

        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel1MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 833, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 385, Short.MAX_VALUE)
        );

        buttonGroup2.add(rdoFill);
        rdoFill.setText("Fill");

        buttonGroup2.add(rdoNotFill);
        rdoNotFill.setSelected(true);
        rdoNotFill.setText("Not fill");

        btnChooseColor.setText("Choose Color");
        btnChooseColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseColorActionPerformed(evt);
            }
        });

        jButton1.setText("Insert Picture");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Insert Text");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdoLine)
                        .addGap(18, 18, 18)
                        .addComponent(rdoRec)
                        .addGap(63, 63, 63)
                        .addComponent(rdoOval))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jButton1)
                        .addGap(68, 68, 68)
                        .addComponent(jButton2)))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdoFill)
                        .addGap(73, 73, 73)
                        .addComponent(rdoNotFill)
                        .addGap(73, 73, 73)
                        .addComponent(btnChooseColor))
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoLine)
                    .addComponent(rdoRec)
                    .addComponent(rdoOval)
                    .addComponent(rdoFill)
                    .addComponent(rdoNotFill)
                    .addComponent(btnChooseColor))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        x1 = evt.getX();
        y1 = evt.getY();

    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseReleased
        // TODO add your handling code here:
        x2 = evt.getX();
        y2 = evt.getY();
        Graphics g = jPanel1.getGraphics(); // lay cong cu de ve hinh
        g.setColor(c);
        switch (shape) {
            case 1:
                g.drawLine(x1, y1, x2, y2);
                break;
            case 2:
                int w = Math.abs(x2 - x1);
                int h = Math.abs(y2 - y1);
                if (x1 < x2 && y1 < y2) {
                    if (rdoNotFill.isSelected()) {
                        g.drawRect(x1, y1, w, h);
                    } else {
                        g.fillRect(x1, y1, w, h);
                    }

                } else if (x1 > x2 && y1 < y2) {
                    if (rdoNotFill.isSelected()) {
                        g.drawRect(x2, y1, w, h);
                    } else {
                        g.fillRect(x2, y1, w, h);
                    }

                } else if (x1 < x2 && y1 > y2) {
                    if (rdoNotFill.isSelected()) {
                        g.drawRect(x1, y2, w, h);
                    } else {
                        g.fillRect(x1, y2, w, h);
                    }

                } else {
                    if (rdoNotFill.isSelected()) {
                        g.drawRect(x2, y2, w, h);
                    } else {
                        g.fillRect(x2, y2, w, h);
                    }

                }

                break;
            case 3:
                w = Math.abs(x2 - x1);
                h = Math.abs(y2 - y1);
                g.drawOval(x1, y1, w, h);
                break;
        }

    }//GEN-LAST:event_jPanel1MouseReleased

    private void rdoRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoRecActionPerformed
        // TODO add your handling code here:
        shape = 2;
    }//GEN-LAST:event_rdoRecActionPerformed

    private void rdoOvalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoOvalActionPerformed
        // TODO add your handling code here:
        shape = 3;
    }//GEN-LAST:event_rdoOvalActionPerformed

    private void rdoLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoLineActionPerformed
        // TODO add your handling code here:
        shape = 1;
    }//GEN-LAST:event_rdoLineActionPerformed

    private void btnChooseColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseColorActionPerformed
        // TODO add your handling code here:
        c = JColorChooser.showDialog(null, "CHon mau", c);
    }//GEN-LAST:event_btnChooseColorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Graphics g = jPanel1.getGraphics();
        ImageIcon icon = new ImageIcon("1.png");
        System.out.println(icon);
        g.drawImage(icon.getImage(), x1, y1, null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Graphics g = jPanel1.getGraphics();
        Font f = new Font("Tahoma",Font.ITALIC,50);
        g.setColor(c);
        g.setFont(f);
        g.drawString("abc", x1+30, y1+30);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        if(xoa == false) xoa = true;
        else
            xoa = false;
    }//GEN-LAST:event_jButton3ActionPerformed

    int preX = 0, preY = 0;
    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved
        // TODO add your handling code here:
        if(xoa == false) return;
        int w = evt.getX();
        
        int h = evt.getY();
        Graphics g = jPanel1.getGraphics();
//        g.setColor(Color.WHITE);
//        g.clearRect(preX - 5,preY - 5, 15, 15);
        
//        g.clearRect(evt.getX() - 5, evt.getY() - 5, 10, 10);
          g.clearRect(evt.getX() , evt.getY() , w, h);
//        g.drawRect(w - 5, h - 5, 10, 10);
//        g.fillRect(w - 5, h - 5, 10, 10);
//        preX = w - 5;
//        preY = h - 5;
//        g.setColor(Color.BLACK);
    }//GEN-LAST:event_jPanel1MouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChooseColor;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rdoFill;
    private javax.swing.JRadioButton rdoLine;
    private javax.swing.JRadioButton rdoNotFill;
    private javax.swing.JRadioButton rdoOval;
    private javax.swing.JRadioButton rdoRec;
    // End of variables declaration//GEN-END:variables
}
