/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import SmartPhone.Brand;
import SmartPhone.SmartPhone;
import java.awt.Component;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.HashMap;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;

/**
 *
 * @author USER
 */
public class mainFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainFrame
     */
//    ArrayList<SmartPhone> list;
    HashMap<Brand, ArrayList<SmartPhone>> h;
    ArrayList<SmartPhone> list;
    Brand br;
    DefaultMutableTreeNode root;
    DefaultMutableTreeNode curBrand = null;
    DefaultMutableTreeNode curSmart = null;
    public static String filename = "data.txt";
    boolean saveforupdate = true;
    boolean saveforupdate2 = true;

    public mainFrame() {
        initComponents();
        setLocationRelativeTo(this);

        loadData();
        txtBrand.setEnabled(false);
        txtCode.setEnabled(false);
        txtName.setEnabled(false);
        txtPlace.setEnabled(false);
        txtPrice.setEnabled(false);

        Set<Brand> keys = h.keySet();
        for (Brand key : keys) {
            list = h.get(key);

            System.out.println(list);
//                 
        }

    }

    void loadData() {
        h = DAO.FileDAO.loadSmartFromFile(filename);
        root = new DefaultMutableTreeNode("Brand");
        DefaultTreeModel model = (DefaultTreeModel) jTree1.getModel();
        model.setRoot(root);
        Set<Brand> keys = h.keySet();
        for (Brand key : keys) {
            DefaultMutableTreeNode node = new DefaultMutableTreeNode(key);
            root.add(node);
            ArrayList<SmartPhone> list = h.get(key);
            for (SmartPhone smartPhone : list) {
                DefaultMutableTreeNode child = new DefaultMutableTreeNode(smartPhone);
                node.add(child);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jPanel2 = new javax.swing.JPanel();
        lblSmartCode = new javax.swing.JLabel();
        lblSmartName = new javax.swing.JLabel();
        lblSmartPlace = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtPlace = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        btnSmartNew = new javax.swing.JButton();
        btnSmartRemove = new javax.swing.JButton();
        btnSmartSave = new javax.swing.JButton();
        UPDATE = new javax.swing.JButton();
        btnSaveToFile = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblBrand = new javax.swing.JLabel();
        txtBrand = new javax.swing.JTextField();
        btnBrandNew = new javax.swing.JButton();
        btnBrandRemove = new javax.swing.JButton();
        btnBrandSave = new javax.swing.JButton();
        btnBrandUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTree1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTree1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SmartPhone Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(102, 102, 255))); // NOI18N

        lblSmartCode.setText("Code");

        lblSmartName.setText("Name");

        lblSmartPlace.setText("Made (place) ");

        jLabel6.setText("Price");

        txtCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodeActionPerformed(evt);
            }
        });

        btnSmartNew.setText("NEW");
        btnSmartNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmartNewActionPerformed(evt);
            }
        });

        btnSmartRemove.setText("REMOVE");
        btnSmartRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmartRemoveActionPerformed(evt);
            }
        });

        btnSmartSave.setText("SAVE");
        btnSmartSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmartSaveActionPerformed(evt);
            }
        });

        UPDATE.setText("UPDATE");
        UPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btnSmartNew, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(btnSmartRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btnSmartSave, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(UPDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addComponent(lblSmartCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSmartName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSmartPlace))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCode)
                            .addComponent(txtName)
                            .addComponent(txtPlace)
                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSmartCode)
                    .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSmartName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSmartPlace)
                    .addComponent(txtPlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSmartNew)
                    .addComponent(btnSmartRemove)
                    .addComponent(btnSmartSave)
                    .addComponent(UPDATE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        btnSaveToFile.setText("SAVE TO FILE");
        btnSaveToFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveToFileActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Brand", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(153, 153, 255))); // NOI18N

        lblBrand.setText("Brand");

        btnBrandNew.setText("NEW");
        btnBrandNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrandNewActionPerformed(evt);
            }
        });

        btnBrandRemove.setText("REMOVE");
        btnBrandRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrandRemoveActionPerformed(evt);
            }
        });

        btnBrandSave.setText("SAVE");
        btnBrandSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrandSaveActionPerformed(evt);
            }
        });

        btnBrandUpdate.setText("UPDATE");
        btnBrandUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrandUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(lblBrand)
                        .addGap(33, 33, 33)
                        .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(btnBrandNew, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnBrandRemove)
                        .addGap(35, 35, 35)
                        .addComponent(btnBrandUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btnBrandSave, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBrand))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBrandNew)
                    .addComponent(btnBrandRemove)
                    .addComponent(btnBrandSave)
                    .addComponent(btnBrandUpdate))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSaveToFile, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnSaveToFile))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodeActionPerformed

    private void btnSmartNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmartNewActionPerformed
        // TODO add your handling code here:
        txtCode.setText("");
        txtName.setText("");
        txtPlace.setText("");
        txtPrice.setText("");
        txtCode.setEnabled(true);
        txtName.setEnabled(true);
        txtPlace.setEnabled(true);
        txtPrice.setEnabled(true);
        saveforupdate = false;

    }//GEN-LAST:event_btnSmartNewActionPerformed

    private void btnBrandUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrandUpdateActionPerformed
        // TODO add your handling code here:
        if (txtBrand.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Please choose brand to update");
            return;
        }
        txtBrand.setEnabled(true);
        saveforupdate2 = true;
    }//GEN-LAST:event_btnBrandUpdateActionPerformed

    void viewBeandAndSmart() {
        Brand br = null;
        SmartPhone sm = null;
        if (curBrand != null) {
            br = (Brand) curBrand.getUserObject();
        }
        if (curSmart != null) {
            sm = (SmartPhone) curSmart.getUserObject();
        }

        txtBrand.setText(br != null ? br.getBrand() : "");
        txtCode.setText(sm != null ? sm.getId() : "");
        txtName.setText(sm != null ? sm.getName() : "");
        txtPlace.setText(sm != null ? sm.getMade() : "");
        txtPrice.setText("" + (sm != null ? sm.getPrice() : ""));
        txtBrand.setEnabled(false);
        txtCode.setEnabled(false);
        txtName.setEnabled(false);
        txtPlace.setEnabled(false);
        txtPrice.setEnabled(false);
    }
    private void jTree1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree1MouseClicked
        

        TreePath path = jTree1.getSelectionPath();
        if (path == null) {
            return;
        }
        DefaultMutableTreeNode selectedNode = null;
        selectedNode = (DefaultMutableTreeNode) path.getLastPathComponent();
        Object selectedObj = selectedNode.getUserObject();

        if (selectedNode == root) {
            curBrand = curSmart = null;
        } else {
            if (selectedObj instanceof Brand) {
                curBrand = selectedNode;
                curSmart = null;
            } else if (selectedObj instanceof SmartPhone) {
                curSmart = selectedNode;
                curBrand = (DefaultMutableTreeNode) selectedNode.getParent();
            }
        }
        viewBeandAndSmart();

    }//GEN-LAST:event_jTree1MouseClicked


    boolean validation() {
        String code = txtCode.getText().toUpperCase();
        String name = txtName.getText().trim();
        String made = txtPlace.getText().trim();

//        Integer salary = Integer.parseInt(txtSalary.getText().toString());
        if (code.isEmpty() || name.isEmpty() || made.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please  fill infpormation", null, JOptionPane.WARNING_MESSAGE);
            return false;

        } else if (!txtCode.getText().toUpperCase().matches("S[0-9]{4}")) {
            JOptionPane.showMessageDialog(null, "Please input format for ID is Sxxxx(x be long to 0-9)", null, JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return true;

    }
    private void btnBrandNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrandNewActionPerformed
        // TODO add your handling code here:
        saveforupdate2 = false;
        txtBrand.setText("");
        txtBrand.setEnabled(true);

    }//GEN-LAST:event_btnBrandNewActionPerformed

    private void btnSmartSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmartSaveActionPerformed
        // TODO add your handling code here:

        if (txtCode.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Please choose smart phone ");
            return;
        }
        if (saveforupdate) {
            DefaultTreeModel model = (DefaultTreeModel) jTree1.getModel();
            if (!validation()) {
                return;
            }
            SmartPhone sm = (SmartPhone) curSmart.getUserObject();
            sm.setName(txtName.getText().trim());
            sm.setMade(txtPlace.getText().trim());
            Integer price = null;

            try {
                price = Integer.parseInt(txtPrice.getText().trim());
                if (price < 0) {
                    JOptionPane.showMessageDialog(null, " Price must greater than or equal 0", null, JOptionPane.WARNING_MESSAGE);
                    return;
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, " Price must a integer number", null, JOptionPane.WARNING_MESSAGE);
                return;
            }
            sm.setPrice(price);
//            loadData();
            txtCode.setEnabled(false);
            txtName.setEnabled(false);
            txtPlace.setEnabled(false);
            txtPrice.setEnabled(false);
            System.out.println(curSmart.getUserObject());
//            model.reload();
        } else {
            if (!validation()) {
                return;
            }

            String code = txtCode.getText().trim().toUpperCase();
            String name = txtName.getText().trim();
            Integer price = null;
            String place = txtPlace.getText().trim();
            try {
                price = Integer.parseInt(txtPrice.getText().trim());
                if (price < 0) {
                    JOptionPane.showMessageDialog(null, " Price must greater than or equal 0", null, JOptionPane.WARNING_MESSAGE);
                    return;
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, " Price must a integer number", null, JOptionPane.WARNING_MESSAGE);
                return;
            }
            SmartPhone sm = new SmartPhone(code, name, place, price);
            curBrand.add(new DefaultMutableTreeNode(sm));


            txtCode.setEnabled(false);
            txtName.setEnabled(false);
            txtPlace.setEnabled(false);
            txtPrice.setEnabled(false);
            txtCode.setText("");
            txtName.setText("");
            txtPlace.setText("");
            txtPrice.setText("");

        }
        jTree1.updateUI();
//        loadData();
    }//GEN-LAST:event_btnSmartSaveActionPerformed

    private void btnSmartRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmartRemoveActionPerformed
        // TODO add your handling code here:
       if(curBrand!=null){
            if (curSmart != null) {
            curBrand.remove(this.curSmart);
            jTree1.updateUI();
            txtCode.setEnabled(false);
            txtName.setEnabled(false);
            txtPlace.setEnabled(false);
            txtPrice.setEnabled(false);
            txtCode.setText("");
            txtName.setText("");
            txtPlace.setText("");
            txtPrice.setText("");
        }
       }
    }//GEN-LAST:event_btnSmartRemoveActionPerformed

    private void UPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATEActionPerformed
        // TODO add your handling code here:
        saveforupdate = true;
        if (txtCode.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Please choose smart phone to update");
            return;
        }
        txtCode.setEnabled(false);
        txtName.setEnabled(true);
        txtPlace.setEnabled(true);
        txtPrice.setEnabled(true);

    }//GEN-LAST:event_UPDATEActionPerformed

    private void btnBrandSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrandSaveActionPerformed
        // TODO add your handling code here:
        if (txtBrand.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Please choose brand");
            return;
        }
        String name = txtBrand.getText().trim();
        if (saveforupdate2) {
            if (txtBrand.getText().length() == 0) {
                return;
            }
            ((Brand) curBrand.getUserObject()).setBrand(name);

        } else {
            if (txtBrand.getText().length() == 0) {
                return;
            }
            Brand br = new Brand(name);
            root.add(new DefaultMutableTreeNode(br));
        }
        jTree1.updateUI();
        txtBrand.setEnabled(false);

    }//GEN-LAST:event_btnBrandSaveActionPerformed

    private void btnBrandRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrandRemoveActionPerformed
        // TODO add your handling code here:
        if (txtBrand.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Please choose brand to remove");
            return;
        }
        root.remove(curBrand);
        jTree1.updateUI();

    }//GEN-LAST:event_btnBrandRemoveActionPerformed

    private void btnSaveToFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveToFileActionPerformed
        // TODO add your handling code here:
        if(root.getChildCount() == 0) return;
        String S;
        try {
            FileWriter f = new FileWriter(filename);
            PrintWriter pf = new PrintWriter(f);
            Enumeration brand = root.children();
            System.out.println(brand.toString());
          
            while(brand.hasMoreElements()){
                DefaultMutableTreeNode brandNode = (DefaultMutableTreeNode) brand.nextElement();
                Brand br = (Brand) brandNode.getUserObject();
                S= "    " +br.getBrand() + ":";
                pf.println(S);
                Enumeration smart = brandNode.children();
                while(smart.hasMoreElements()){
                    DefaultMutableTreeNode smartt = (DefaultMutableTreeNode) smart.nextElement();
                    SmartPhone sm = (SmartPhone) smartt.getUserObject();
                    S = "       "+sm.getId() + "-" + sm.getName() + "-" + sm.getMade() + "-" + sm.getPrice();
                    pf.println(S);
                }
            }
            pf.close();
            f.close();
            JOptionPane.showMessageDialog(this, "Save successfull");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSaveToFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton UPDATE;
    private javax.swing.JButton btnBrandNew;
    private javax.swing.JButton btnBrandRemove;
    private javax.swing.JButton btnBrandSave;
    private javax.swing.JButton btnBrandUpdate;
    private javax.swing.JButton btnSaveToFile;
    private javax.swing.JButton btnSmartNew;
    private javax.swing.JButton btnSmartRemove;
    private javax.swing.JButton btnSmartSave;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    private javax.swing.JLabel lblBrand;
    private javax.swing.JLabel lblSmartCode;
    private javax.swing.JLabel lblSmartName;
    private javax.swing.JLabel lblSmartPlace;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPlace;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables
}
