/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internationalzation;

import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class Inter_Emp_Mng extends javax.swing.JFrame {

    /**
     * Creates new form Inter_Emp_Mng
     */
    String language;
    String country;
    ResourceBundle resource;
    Locale current;

    public Inter_Emp_Mng(String language, String country) {
        initComponents();
//        this.setSize(280, 250);
        this.setLocationRelativeTo(null);
        this.language = language;
        this.country = country;
        this.country = country;

    }

    public Inter_Emp_Mng() {
        initComponents();
         this.setLocationRelativeTo(null);
        setUpGUI();
    }

    public void setUpGUI() {
        if (jradioVietNamese.isSelected()) {
            current = new Locale("vn", "VN");

        } else {
            current = new Locale("en", "US");
        }
        Locale currentLocale;
//        currentLocale = new Locale(language, country);
        String base = "language.Resources";
      
        resource = ResourceBundle.getBundle(base, current);
          this.setTitle(resource.getString("title"));
        lblCode.setText(resource.getString("lblCode"));
        lblName.setText(resource.getString("lblName"));
        lblAge.setText(resource.getString("lblAge"));
        lblSex.setText(resource.getString("lblSex"));
        jRadioButton1.setText(resource.getString("jRadioButton1"));
        jradio2.setText(resource.getString("jradio2"));
        btnOK.setText(resource.getString("btnOK"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        lblCode = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblSex = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jradio2 = new javax.swing.JRadioButton();
        txtAge = new javax.swing.JTextField();
        btnOK = new javax.swing.JButton();
        jradioEnglish = new javax.swing.JRadioButton();
        jradioVietNamese = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Emplyee Manager");

        lblCode.setText("Code");

        lblName.setText("Name");

        lblSex.setText("Sex");

        lblAge.setText("Age");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Male");

        buttonGroup1.add(jradio2);
        jradio2.setText("Female");

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        buttonGroup2.add(jradioEnglish);
        jradioEnglish.setSelected(true);
        jradioEnglish.setText("English");
        jradioEnglish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jradioEnglishActionPerformed(evt);
            }
        });

        buttonGroup2.add(jradioVietNamese);
        jradioVietNamese.setText("VietNamese");
        jradioVietNamese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jradioVietNameseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCode)
                            .addComponent(lblName)
                            .addComponent(lblSex)
                            .addComponent(lblAge))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jradio2))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCode)
                                .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(btnOK))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jradioEnglish)
                        .addGap(44, 44, 44)
                        .addComponent(jradioVietNamese)))
                .addContainerGap(198, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCode)
                    .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSex)
                    .addComponent(jRadioButton1)
                    .addComponent(jradio2))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAge)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnOK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jradioEnglish)
                    .addComponent(jradioVietNamese))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
        if(txtCode.getText().trim().isEmpty()){
            return;
        }
        String msgTitle = resource.getString("msgTitle");
        int age = Integer.parseInt(txtAge.getText());
        String msg = null;
        if (jradioEnglish.isSelected()) {
            if (jRadioButton1.isSelected()) {
                msg = "Code:" + txtCode.getText() + "\nName:" + txtName.getText() + "\nSex:" + jRadioButton1.getText() + "\nAge:" + txtAge.getText();
            } else {
                msg = "Code:" + txtCode.getText() + "\nName:" + txtName.getText() + "\nSex:" + jradio2.getText() + "\nAge:" + txtAge.getText();
            }
             JOptionPane.showMessageDialog(this,msg, msgTitle, 1);
        } else {
            if (jRadioButton1.isSelected()) {
                msg = "Mã :" + txtCode.getText() + "\nTên:" + txtName.getText() + "\nGiới Tính:" + jRadioButton1.getText() + "\nTuổi:" + txtAge.getText();
            } else {
                msg = "Mã:" + txtCode.getText() + "\nTên:" + txtName.getText() + "\nGiới Tính:" + jradio2.getText() + "\nTuổi:" + txtAge.getText();
            }
             JOptionPane.showMessageDialog(this,msg, msgTitle, 1);
        }

       
    }//GEN-LAST:event_btnOKActionPerformed

    private void jradioEnglishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jradioEnglishActionPerformed
        // TODO add your handling code here:
        jradioEnglish.setSelected(true);
        setUpGUI();
    }//GEN-LAST:event_jradioEnglishActionPerformed

    private void jradioVietNameseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jradioVietNameseActionPerformed
        // TODO add your handling code here:
        jradioVietNamese.setSelected(true);
        setUpGUI();
    }//GEN-LAST:event_jradioVietNameseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inter_Emp_Mng.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inter_Emp_Mng.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inter_Emp_Mng.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inter_Emp_Mng.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        final String language;
        final String country;
        if (args.length != 2) {

            language = new String("vn");
            country = new String("VN");
        } else {
            language = new String("en");
            country = new String("US");
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inter_Emp_Mng().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jradio2;
    private javax.swing.JRadioButton jradioEnglish;
    private javax.swing.JRadioButton jradioVietNamese;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblCode;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSex;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
