/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gamepuzzle;

import java.awt.FlowLayout;
import java.awt.Frame;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author USER
 */
public class DemoLayoutt extends javax.swing.JPanel {

    /**
     * Creates new form DemoLayoutt
     */
    JPanel tren, duoi;
    int SIZE = 3;
    JButton[] btns;
    JLabel jlb1, jlb2, jlb3;
    JComboBox<String> cbx;
    JButton btnNew;
    int moveCount = 0;
    int time = 0;

    public DemoLayoutt() {
        initComponents();
        loadControl();
        setLayout(new GridLayout(2, 1));
       
    }
    public  void loadControl(){
        
        // xoa cac control cu
        removeAll();
        tren = new JPanel(new GridLayout(SIZE, SIZE));
        duoi = new JPanel(new FlowLayout(FlowLayout.CENTER));
        add(tren);
        add(duoi);
        // tao chi tiet cho "tren"
         btns = new JButton[SIZE * SIZE];
        ArrayList nhannut = new ArrayList();
        for(int i = 0; i < SIZE*SIZE;i++){
            nhannut.add(i);
        }
        Collections.shuffle(nhannut);
       for(int i = 0; i < SIZE*SIZE;i++){
           btns[i] = new JButton(nhannut.get(i)+ "");
       }
       for(int i = 0 ; i < SIZE*SIZE;i++){
           tren.add(btns[i]);
           // them event vao da btns
           btns[i].addActionListener(new ActionListener() {
               @Override
               public void actionPerformed(ActionEvent e) {
//                   e.getSource();// tra ve controll vua bi click
                   JOptionPane.showMessageDialog(null, ((JButton)e.getSource()).getText());
               }
           });
       }
       
       // tao chi tiet cho panel duoi
       jlb1 = new JLabel("Move count:" + moveCount);
       jlb2 = new JLabel("Time:" + time);
       jlb3 = new JLabel("Choose size");
       String[] items = {"3x3","4x4","5x5"};
       cbx = new JComboBox<>(items);
       btnNew = new JButton("New game");
       duoi.add(jlb1);
       duoi.add(jlb2);
       duoi.add(jlb3);
       duoi.add(cbx);
       duoi.add(btnNew);
        // them event
        cbx.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int pos = cbx.getSelectedIndex();
                switch(pos){
                    case 0:
                        SIZE = 3;
                        break;
                    case 1:
                        SIZE = 4;
                        break;
                    case 2:
                        SIZE = 5;
                        break;
                }
            }
        });
        
        // them event vao btnNew
        
        btnNew.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                loadControl();
             Frame[] f =JFrame.getFrames();
             f[0].setSize(400+SIZE, 300+SIZE);
            }
        });
//        this.getParent().setSize(300, 300);
//                 this.setSize(500,500);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
